### ISSUE TITLE
Error: Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by icandura** [ronald8192/ComicDownloader-ikanman#1]
After I running `npm install`
it return `npm WARN comic-downloader-ikanman@1.0.0 No repository field.`
Then I running `node main.js 1544`
```shell
module.js:471
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/ComicDownloader-ikanman/node_modules/node-opencc/src/index.js:6:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by ronald8192** [comment]
Seems `npm install` did not download `bluebird` (one of the dependency of `node-opencc`). You can use `npm install bluebird` to install it.

But the download part (`download.rb`) is not working anymore since ikanman add additional checking on server side. I might fix it if I have time.

You can still use `main.js` to get the image url list. It downloaded to `download/chapters.json`

**Comment by icandura** [comment]
It works, thank you~
